"""
Figure 3: Bayesian MCMC Posterior Diagnostics for β
Author: Wealth Dynamics Lab
Date: 2026
Purpose: Generate Figure 3 with posterior distribution histogram,
         trace plot, autocorrelation function, and ESS diagnostics.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf

def generate_figure3():
    """
    Load MCMC posterior draws and create Figure 3 diagnostics.
    """
    # Load posterior samples generated by mcmc_posterior.py
    df = pd.read_csv('data/mcmc_posterior_draws.csv')
    posterior = df['beta_draw'].values
    
    # Create figure with 4 panels
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    
    # Panel 1: Posterior distribution (main histogram)
    axes[0, 0].hist(posterior, bins=80, density=True, alpha=0.75, color='steelblue', edgecolor='black')
    mean_beta = np.mean(posterior)
    axes[0, 0].axvline(mean_beta, color='red', linestyle='--', linewidth=2, label=f'Mean β = {mean_beta:.4f}')
    axes[0, 0].set_title('Posterior Distribution of β')
    axes[0, 0].set_xlabel('β (Edge Extraction Coefficient)')
    axes[0, 0].set_ylabel('Density')
    axes[0, 0].legend()
    
    # Panel 2: Trace plot (first 2000 iterations shown)
    axes[0, 1].plot(posterior[:2000], alpha=0.7, color='darkblue')
    axes[0, 1].set_title('Trace Plot')
    axes[0, 1].set_xlabel('Iteration')
    axes[0, 1].set_ylabel('β')
    
    # Panel 3: Autocorrelation function
    plot_acf(posterior, lags=50, ax=axes[1, 0])
    axes[1, 0].set_title('Autocorrelation Function (ACF)')
    
    # Panel 4: ESS calculation and summary
    # Effective Sample Size
    ess = len(posterior) / (1 + 2 * np.sum(np.correlate(posterior - np.mean(posterior),
                                                         posterior - np.mean(posterior),
                                                         mode='full')[len(posterior):] / np.var(posterior)))
    
    axes[1, 1].text(0.5, 0.5, f'Effective Sample Size (ESS)\n\n{ess:.0f}\n\n'
                              f'Posterior Mean: {mean_beta:.4f}\n'
                              f'95% HPD: [{np.percentile(posterior, 2.5):.4f}, '
                              f'{np.percentile(posterior, 97.5):.4f}]',
                    horizontalalignment='center', verticalalignment='center',
                    fontsize=14, transform=axes[1, 1].transAxes)
    axes[1, 1].set_title('MCMC Diagnostics Summary')
    axes[1, 1].axis('off')
    
    plt.suptitle('Figure 3: Bayesian MCMC Posterior Diagnostics for β', fontsize=16)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    
    # Save high-resolution figure
    plt.savefig('figure3_mcmc_diagnostics.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    print("Figure 3 generated successfully!")
    print("Saved as: figure3_mcmc_diagnostics.png")
    print(f"Posterior mean of β: {mean_beta:.4f}")
    print(f"Effective Sample Size (ESS): {ess:.0f}")

if __name__ == "__main__":
    generate_figure3()
